plugins {
    id "java"
    id "application"
}

repositories {
    mavenCentral()
}

java {
    
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
}

tasks.test {
    useJUnitPlatform()
}

application {
 
    mainClass.set("edu.odu.cs.cs417.Main")
    
}
//Program restricted to [0,1)]
//Change the argument here to test with different inputs
tasks.named("run") {
     
}
